### ISSUE TITLE
Error on installation.

### ISSUE THREAD

**Issue by ggb667** [RuntimeTools/appmetrics-elk#31]
It's complaining about an unsupported version of nodejs?  I upgraded from v8.9.3 to v8.9.4, no difference.  Also tried installing globally and from an elevated command prompt and powershell.  Also checked the NPM was up to date an cleared its cache and retried.  No dice.
C:\wk\ms-guest>npm install appmetrics-elk -g
> appmetrics@1.2.0 install C:\Users\username\AppData\Roaming\npm\node_modules\appmetrics-elk\node_modules\appmetrics
> node extract_all_binaries.js
...
Unsupported version v8.9.4. Exiting.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! appmetrics@1.2.0 install: `node extract_all_binaries.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the appmetrics@1.2.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\username\AppData\Roaming\npm-cache\_logs\2018-01-03T22_24_05_235Z-debug.log

A look at the file C:\Users\username\AppData\Roaming\npm-cache\_logs\2018-01-03T22_24_05_235Z-debug.log is unenlightening.

...
945 verbose unlock done using C:\Users\username\AppData\Roaming\npm-cache\_locks\staging-be97e82908d22341.lock for C:\Users\username\AppData\Roaming\npm\node_modules\.staging
946 verbose stack Error: appmetrics@1.2.0 install: `node extract_all_binaries.js`
946 verbose stack Exit status 1
946 verbose stack     at EventEmitter.<anonymous> (C:\Users\username\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\index.js:285:16)
946 verbose stack     at emitTwo (events.js:126:13)
946 verbose stack     at EventEmitter.emit (events.js:214:7)
946 verbose stack     at ChildProcess.<anonymous> (C:\Users\username\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
946 verbose stack     at emitTwo (events.js:126:13)
946 verbose stack     at ChildProcess.emit (events.js:214:7)
946 verbose stack     at maybeClose (internal/child_process.js:925:16)
946 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
947 verbose pkgid appmetrics@1.2.0
948 verbose cwd C:\wk\ms-guest
949 verbose Windows_NT 10.0.15063
950 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\username\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "appmetrics-elk" "-g"
951 verbose node v8.9.4
952 verbose npm  v5.6.0
953 error code ELIFECYCLE
954 error errno 1
955 error appmetrics@1.2.0 install: `node extract_all_binaries.js`
955 error Exit status 1
956 error Failed at the appmetrics@1.2.0 install script.
956 error This is probably not a problem with npm. There is likely additional logging output above.
957 verbose exit [ 1, true ]

I'm a bit green with node and npm, but I think I'm doing things right.  Anyone have any ideas what else I can try?

**Comment by tobespc** [comment]
We need to update the version of appmetrics that appmetrics-elk uses.  1.2.0 is very old

**Comment by ggb667** [comment]
Is this connector being actively maintained?  No new versions in 2 years and it won't install with the current version of nodejs.  I've not updated and maintained code in github that someone else created.  I understand I can create a branch of my own and merge in the 2 pull requests that are outstanding, but I'm afraid I'd mess something up.

**Comment by tonifirnandes** [comment]
Hello sir @ggb667 and sir @tobespc , sorry i am getting this error as well. Any suggestion for this, thanks.
